services:
  app:
    build:
      context: .
      target: prod
    ports:
      - "${APP_PORT:-3000}:80"
    env_file: envs/app.env
    volumes:
      - ./app-data:/var/lib/cecyl/data

  db:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "5000:27017"
    # TODO: replace with secret
    env_file: envs/db.env
    volumes:
      - ./db/data:/data/db
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping")' --quiet
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
