services:
  app:
    build:
      target: devcontainer
    ports:
      - "${APP_PORT:-3000}:80"
    volumes:
      - .:/workspaces/cecyl-backend:cached
    command: sleep infinity

  db:
    volumes: !override
      - ./db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    env_file: envs/mongo-express.env
    depends_on:
      db:
        condition: service_healthy
