entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: true

providers:
  docker:
    exposedbydefault: false
  file:
    filename: "/dynamic-configs.yaml"

log:
  level: INFO

accesslog: true

api:
  dashboard: true
  insecure: true